### ISSUE TITLE
一个用例调用多个步骤，会报错

### ISSUE THREAD

**Issue by cindy3124** [FuckyouBB/extent_report_template_httprunner2#1]
如果一个用例调用了多个步骤，像这样的：

![image](https://user-images.githubusercontent.com/26869514/86319175-7727bb00-bc66-11ea-9895-e8359bddaba1.png)

使用自定义的这个模版  就会报错：

`Traceback (most recent call last):
  File "init.py", line 55, in <module>
    run(suite_path, conf, fail_fast)
  File "init.py", line 35, in run
    report_path = gen_html_report(summary, report_template='./template/extent-theme-template.html')
  File "D:\Programs\Python\Python37\lib\site-packages\httprunner\report\html\gen_report.py", line 58, in gen_html_report
    ).render(summary)
  File "D:\Programs\Python\Python37\lib\site-packages\jinja2\asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "D:\Programs\Python\Python37\lib\site-packages\jinja2\environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "D:\Programs\Python\Python37\lib\site-packages\jinja2\environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Programs\Python\Python37\lib\site-packages\jinja2\_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "<template>", line 270, in top-level template code
  File "D:\Programs\Python\Python37\lib\site-packages\jinja2\environment.py", line 430, in getattr
    return getattr(obj, attribute)
jinja2.exceptions.UndefinedError: 'list object' has no attribute 'stat'`

这样的有解么？

**Comment by FuckyouBB** [comment]
用例怎么写能让一个case里有6个log

**Comment by cindy3124** [comment]
> 用例怎么写能让一个case里有6个log

testcases目录下：case1.yml调用6个api，case2.yml调用case1，看报告就可以看到：case2的detail有6个log了

**Comment by FuckyouBB** [comment]
优化了
